name: CI (docs)

on:
    pull_request:
        branches:
            - main
        # Ensure that the documentation can be rebuilt on documentation and library source changes.
        paths:
            - "docs/**"
            - "src/**"

jobs:
    ci:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 12.x

            # Note that we include the built library, to keep examples up-to-date.

            - name: Install dependancies
              run: yarn install --frozen-lockfile

            - name: Build library
              run: yarn build

            # Build the actual site. Note that we do not deploy it, we just check if it builds without errors.

            - name: Install Docusaurus
              run: yarn install --frozen-lockfile
              working-directory: ./docs

            - name: Build
              run: yarn build
              working-directory: ./docs
