name: Deploy Docs

on:
    push:
        branches: [v3]
    workflow_dispatch:

permissions:
    contents: read
    deployments: write

concurrency:
    group: deploy-docs-${{ github.ref }}
    cancel-in-progress: true

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7
            - uses: oven-sh/setup-bun@v2
            - run: bun install --frozen-lockfile
            - run: bun install --frozen-lockfile --cwd docs
            - run: bun run build:docs
            - uses: cloudflare/wrangler-action@v4
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  command: pages deploy docs/dist --project-name=party-js-v3
                  gitHubToken: ${{ secrets.GITHUB_TOKEN }}
